### ISSUE TITLE
Use time as version

### ISSUE THREAD

**Issue by yrliou** [brave/go-sync#69]
Currently our version is a sequential number increased by 1 each time, we should use timestamp instead, which is also used by chromium, otherwise we will encounter issue when de-duplicating records with client tag.
cc @AlexeyBarabash

**Comment by AlexeyBarabash** [comment]
The STR to test the issue, can't find them anywhere, plus some comments on details

```

1. create sync chain on deviceA, copy code, enable open tabs sync type;
2. connect deviceB, disable bookmarks, enable open tabs sync type;
3. on deviceB open brave://history/syncedTabs
4. on deviceA open new tab with google.com site;
5. on deviceA search "1"; wait 5 sec;
6. on deviceA search "12"; wait 5 sec;
7. on deviceA search "123"; wait 5 sec;
8. on deviceB wait till tab "Google - 123" appears;
9. close browser on deviceB
10. on deviceA close tab with search
11. wait 12 seconds
12. Restore closed tab, Ctrl+Shift+T on Linux; wait 1 sec;
13. on deviceA search "123A";   wait 5 sec;
14. on deviceA close tab with search
15. wait 12 seconds
16. on deviceA search "123AB";  wait 5 sec;
17. on deviceB launch browser

ACTUAL:
18. on deviceB brave://history/syncedTabs there are no tabs

EXPECTED:
19. on deviceB brave://history/syncedTabs there is a tab of search "123AB"

```


I have made a few attempts to see the issue on Chromium and found why it is impossible to reproduce it - Chromium uses time_t as the version.

So with Brave versions of records with the same `client_defined_unique_tag` may look as:
```
request:  0
response: 1
...
request:  5, "deleted": true,
response: 6, "deleted": true,
request:  6, "deleted": false,
response: 7, "deleted": false,
...
request:  12, "deleted": true,
response: 13, "deleted": true,
request:  0, "deleted": false,
response: 1, "deleted": false, // this is ignored by ProcessorEntity::UpdateIsReflection()
```

And Chrome:
```
request  - "version": "0"
response - "version": "1621343273099480"

request -  "version": "1621343273099480"
response - "version": "1621343284154730"
```

This does nothing with `ModelTypeWorker::DeduplicatePendingUpdatesBasedOnClientTagHash()`, because if duplicated records with the same tag hash arrive, only the newest remains.
But having the version as server side time_t allows to pass `ProcessorEntity::UpdateIsReflection()` check in `ClientTagBasedRemoteUpdateHandler::ProcessUpdate` and don't got ignored.
