### ISSUE TITLE
New Sync Clients not allowed to join sync (throttled)

### ISSUE THREAD

**Issue by andrewpayne68** [brave/go-sync#95]
Latest Build prevents sync on any new devices  - error is below

01/08/2022, 12:05:05 PM GetUpdates Response
Received error: SERVER_RETURN_THROTTLED
{
"client_command": {
"max_commit_batch_size": "90",
"sessions_commit_delay_seconds": "11",
"set_sync_poll_interval": "30"
},
"error_code": "THROTTLED",
"error_message": "exceed limit of active devices in a chain",
"get_updates": {},
"store_birthday": "1"
}

**Comment by tycho** [comment]
Related [forum topic](https://community.brave.com/t/unable-to-join-brave-sync-due-to-exceeding-active-device-limit-and-cannot-access-device-list-to-remove-any-devices/311304/16) from which this issue is derived.

My sync chain admittedly does have a lot of devices on it (16 at the moment) because several of them dual boot between Linux and Windows, and some of them (Macs primarily) have virtual machines with Brave installed in them. I think the intended limit is 20 devices (because of 161c64a0bc9e3cdbc436b4323354974a94ae4409). That limit is arguably rather low, though I should be below it at the moment. So I suspect the limit is not being correctly applied in some way.

Also, I assume that limit was added due to resource constraints on Brave's server infrastructure. I'd be happy to self-host a sync server, though I would need to find a good way to tell Brave to use a custom sync server URL. It seems you can do it with the `--sync-url=` command line flag, but it would be nice if there was a [Group Policy](https://support.brave.com/hc/en-us/articles/360039248271-Group-Policy) option to control this -- Google doesn't provide one, so Brave would need to add a new one for it. I would rather not be forced to edit all the Brave shortcuts on Windows machines in order to use a custom sync server, and I'm not even sure how to add custom command line flags for macOS systems, without resorting to using a terminal or shell script.

**Comment by fmarier** [comment]
Thanks for reporting this. We will be temporarily raising the limit to 50 until we've addressed all of the underlying issues: https://github.com/brave/go-sync/pull/96

**Comment by tycho** [comment]
> Thanks for reporting this. We will be temporarily raising the limit to 50 until we've addressed all of the underlying issues: #96

Can you also add some UI elements to explain why the sync is breaking? On clients that fail to get added to the sync chain, the sync UI in Settings just breaks (can't toggle anything for example). If I didn't know about the `brave://sync-internals` URL I wouldn't have found why it was not syncing properly.

Also if there were some UI elements for all clients (whether they were added to the sync chain successfully or not) indicating how many devices are in the chain vs. how many are allowed by the server, that would be useful as well.

**Comment by fmarier** [comment]
@tycho That's a good suggestion. Would you mind opening an issue on https://github.com/brave/brave-browser/issues/new so that we can track it in the right repo? go-sync is just for the backend server.

**Comment by andrewpayne68** [comment]
> Thanks for reporting this. We will be temporarily raising the limit to 50 until we've addressed all of the underlying issues: #96

Thank you! I can now sync my new laptop. Cheers
